language: node_js
node_js:
- node
warnings_are_errors: false
install:
- npm install
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Oqj+TZCYl0BuJWPqfyuI9k9Oidrz5or7cWVjy33+Vv+EGchvOvp6PRknHnu/YEwsaO3+RfDbWfREtZuBiaY8ZFAZHOQR1Wbi/B59x3P4Yj6sjjoJfuDm26DAYKJ+ct8iqiufEO+8wlJaAcfDHsbkV2OrP1Bb0xj9wLqwDjnNNsSHf3V+2JbC2vUTW5eILYUP4aKYtcQchOKU3D+T15hJ7uBxuLTFKe3tYr4Xy7I2ozImEj64MJFNeRatjRw9lKXev/hwaN23RyTvkwlttYLnDWw4t7QTK7sB3OHVW18zGfMnAsKs0fud1fqoENIrZ/u3G66ag8r5VwhDZkfJsI+yBULcmhLLKdoV8ppgyKHH+klul42/H38pZ8Qe3Q67DrKTw8pOENmo/PORZusym7uJuZ9/nbssQf/myKsfm/CHF5HQjrAJrdWzmWUL21h0f+tQPeryg2K8e9aoeo6WYM+6l7IHiom1BP/tdQEHKTGXERxg2N0ll5S3PH6BTPMGvsz72BoqGDSinWf0wtAVa+H565kTv8glpyQKKyn2qskZ9OJjzVxbgFV81TepAcMhIU1AfrC6jf9o3rXpWcQty32oMs/JJvTcGmYVzoGIZ5rYGjIbqfg71/1vzXm2xSEttFrLZsQf02pFO39CR23RhLido74VUaytK8cqkvdKLfaZbkw=
